// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"khalif-alquran/internal/config"
	"khalif-alquran/internal/handler"
	"khalif-alquran/internal/repository"
	"khalif-alquran/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	surahRepository := repository.NewSurahRepository(db)
	ayahRepository := repository.NewAyahRepository(db)
	redisRepository := repository.NewRedisRepository(client)
	quranUC := usecase.NewQuranUseCase(surahRepository, ayahRepository, redisRepository)
	quranHandler := handler.NewQuranHandler(quranUC)
	bookmarkRepository := repository.NewBookmarkRepository(db)
	bookmarkUC := usecase.NewBookmarkUseCase(bookmarkRepository)
	bookmarkHandler := handler.NewBookmarkHandler(bookmarkUC)
	app := NewApp(db, client, quranHandler, bookmarkHandler)
	return app, nil
}
