// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: api/proto/quran.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuranService_GetAllSurahs_FullMethodName   = "/quran.QuranService/GetAllSurahs"
	QuranService_GetSurahDetail_FullMethodName = "/quran.QuranService/GetSurahDetail"
)

// QuranServiceClient is the client API for QuranService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuranServiceClient interface {
	GetAllSurahs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SurahListResponse, error)
	GetSurahDetail(ctx context.Context, in *SurahDetailRequest, opts ...grpc.CallOption) (*SurahDetailResponse, error)
}

type quranServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuranServiceClient(cc grpc.ClientConnInterface) QuranServiceClient {
	return &quranServiceClient{cc}
}

func (c *quranServiceClient) GetAllSurahs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SurahListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurahListResponse)
	err := c.cc.Invoke(ctx, QuranService_GetAllSurahs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quranServiceClient) GetSurahDetail(ctx context.Context, in *SurahDetailRequest, opts ...grpc.CallOption) (*SurahDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurahDetailResponse)
	err := c.cc.Invoke(ctx, QuranService_GetSurahDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuranServiceServer is the server API for QuranService service.
// All implementations must embed UnimplementedQuranServiceServer
// for forward compatibility.
type QuranServiceServer interface {
	GetAllSurahs(context.Context, *Empty) (*SurahListResponse, error)
	GetSurahDetail(context.Context, *SurahDetailRequest) (*SurahDetailResponse, error)
	mustEmbedUnimplementedQuranServiceServer()
}

// UnimplementedQuranServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuranServiceServer struct{}

func (UnimplementedQuranServiceServer) GetAllSurahs(context.Context, *Empty) (*SurahListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSurahs not implemented")
}
func (UnimplementedQuranServiceServer) GetSurahDetail(context.Context, *SurahDetailRequest) (*SurahDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSurahDetail not implemented")
}
func (UnimplementedQuranServiceServer) mustEmbedUnimplementedQuranServiceServer() {}
func (UnimplementedQuranServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuranServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuranServiceServer will
// result in compilation errors.
type UnsafeQuranServiceServer interface {
	mustEmbedUnimplementedQuranServiceServer()
}

func RegisterQuranServiceServer(s grpc.ServiceRegistrar, srv QuranServiceServer) {
	// If the following call panics, it indicates UnimplementedQuranServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuranService_ServiceDesc, srv)
}

func _QuranService_GetAllSurahs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuranServiceServer).GetAllSurahs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuranService_GetAllSurahs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuranServiceServer).GetAllSurahs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuranService_GetSurahDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurahDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuranServiceServer).GetSurahDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuranService_GetSurahDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuranServiceServer).GetSurahDetail(ctx, req.(*SurahDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuranService_ServiceDesc is the grpc.ServiceDesc for QuranService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuranService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quran.QuranService",
	HandlerType: (*QuranServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSurahs",
			Handler:    _QuranService_GetAllSurahs_Handler,
		},
		{
			MethodName: "GetSurahDetail",
			Handler:    _QuranService_GetSurahDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/quran.proto",
}
