// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: quran.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_quran_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{0}
}

type Surah struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LatinName      string                 `protobuf:"bytes,3,opt,name=latin_name,json=latinName,proto3" json:"latin_name,omitempty"`
	EnglishName    string                 `protobuf:"bytes,4,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	IndonesianName string                 `protobuf:"bytes,7,opt,name=indonesian_name,json=indonesianName,proto3" json:"indonesian_name,omitempty"` // FIELD BARU
	RevelationType string                 `protobuf:"bytes,5,opt,name=revelation_type,json=revelationType,proto3" json:"revelation_type,omitempty"`
	TotalAyahs     int32                  `protobuf:"varint,6,opt,name=total_ayahs,json=totalAyahs,proto3" json:"total_ayahs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Surah) Reset() {
	*x = Surah{}
	mi := &file_quran_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Surah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Surah) ProtoMessage() {}

func (x *Surah) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Surah.ProtoReflect.Descriptor instead.
func (*Surah) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{1}
}

func (x *Surah) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Surah) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Surah) GetLatinName() string {
	if x != nil {
		return x.LatinName
	}
	return ""
}

func (x *Surah) GetEnglishName() string {
	if x != nil {
		return x.EnglishName
	}
	return ""
}

func (x *Surah) GetIndonesianName() string {
	if x != nil {
		return x.IndonesianName
	}
	return ""
}

func (x *Surah) GetRevelationType() string {
	if x != nil {
		return x.RevelationType
	}
	return ""
}

func (x *Surah) GetTotalAyahs() int32 {
	if x != nil {
		return x.TotalAyahs
	}
	return 0
}

type Ayah struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	TextArabic    string                 `protobuf:"bytes,2,opt,name=text_arabic,json=textArabic,proto3" json:"text_arabic,omitempty"`
	TextLatin     string                 `protobuf:"bytes,3,opt,name=text_latin,json=textLatin,proto3" json:"text_latin,omitempty"`
	Translation   string                 `protobuf:"bytes,4,opt,name=translation,proto3" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ayah) Reset() {
	*x = Ayah{}
	mi := &file_quran_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ayah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ayah) ProtoMessage() {}

func (x *Ayah) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ayah.ProtoReflect.Descriptor instead.
func (*Ayah) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{2}
}

func (x *Ayah) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Ayah) GetTextArabic() string {
	if x != nil {
		return x.TextArabic
	}
	return ""
}

func (x *Ayah) GetTextLatin() string {
	if x != nil {
		return x.TextLatin
	}
	return ""
}

func (x *Ayah) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type SurahListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surahs        []*Surah               `protobuf:"bytes,1,rep,name=surahs,proto3" json:"surahs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurahListResponse) Reset() {
	*x = SurahListResponse{}
	mi := &file_quran_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurahListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurahListResponse) ProtoMessage() {}

func (x *SurahListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurahListResponse.ProtoReflect.Descriptor instead.
func (*SurahListResponse) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{3}
}

func (x *SurahListResponse) GetSurahs() []*Surah {
	if x != nil {
		return x.Surahs
	}
	return nil
}

type SurahDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurahDetailRequest) Reset() {
	*x = SurahDetailRequest{}
	mi := &file_quran_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurahDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurahDetailRequest) ProtoMessage() {}

func (x *SurahDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurahDetailRequest.ProtoReflect.Descriptor instead.
func (*SurahDetailRequest) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{4}
}

func (x *SurahDetailRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SurahDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surah         *Surah                 `protobuf:"bytes,1,opt,name=surah,proto3" json:"surah,omitempty"`
	Ayahs         []*Ayah                `protobuf:"bytes,2,rep,name=ayahs,proto3" json:"ayahs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurahDetailResponse) Reset() {
	*x = SurahDetailResponse{}
	mi := &file_quran_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurahDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurahDetailResponse) ProtoMessage() {}

func (x *SurahDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quran_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurahDetailResponse.ProtoReflect.Descriptor instead.
func (*SurahDetailResponse) Descriptor() ([]byte, []int) {
	return file_quran_proto_rawDescGZIP(), []int{5}
}

func (x *SurahDetailResponse) GetSurah() *Surah {
	if x != nil {
		return x.Surah
	}
	return nil
}

func (x *SurahDetailResponse) GetAyahs() []*Ayah {
	if x != nil {
		return x.Ayahs
	}
	return nil
}

var File_quran_proto protoreflect.FileDescriptor

const file_quran_proto_rawDesc = "" +
	"\n" +
	"\vquran.proto\x12\x05quran\"\a\n" +
	"\x05Empty\"\xe8\x01\n" +
	"\x05Surah\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"latin_name\x18\x03 \x01(\tR\tlatinName\x12!\n" +
	"\fenglish_name\x18\x04 \x01(\tR\venglishName\x12'\n" +
	"\x0findonesian_name\x18\a \x01(\tR\x0eindonesianName\x12'\n" +
	"\x0frevelation_type\x18\x05 \x01(\tR\x0erevelationType\x12\x1f\n" +
	"\vtotal_ayahs\x18\x06 \x01(\x05R\n" +
	"totalAyahs\"\x80\x01\n" +
	"\x04Ayah\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1f\n" +
	"\vtext_arabic\x18\x02 \x01(\tR\n" +
	"textArabic\x12\x1d\n" +
	"\n" +
	"text_latin\x18\x03 \x01(\tR\ttextLatin\x12 \n" +
	"\vtranslation\x18\x04 \x01(\tR\vtranslation\"9\n" +
	"\x11SurahListResponse\x12$\n" +
	"\x06surahs\x18\x01 \x03(\v2\f.quran.SurahR\x06surahs\",\n" +
	"\x12SurahDetailRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"\\\n" +
	"\x13SurahDetailResponse\x12\"\n" +
	"\x05surah\x18\x01 \x01(\v2\f.quran.SurahR\x05surah\x12!\n" +
	"\x05ayahs\x18\x02 \x03(\v2\v.quran.AyahR\x05ayahs2\x8f\x01\n" +
	"\fQuranService\x126\n" +
	"\fGetAllSurahs\x12\f.quran.Empty\x1a\x18.quran.SurahListResponse\x12G\n" +
	"\x0eGetSurahDetail\x12\x19.quran.SurahDetailRequest\x1a\x1a.quran.SurahDetailResponseB\x17Z\x15khalif-alquran/pkg/pbb\x06proto3"

var (
	file_quran_proto_rawDescOnce sync.Once
	file_quran_proto_rawDescData []byte
)

func file_quran_proto_rawDescGZIP() []byte {
	file_quran_proto_rawDescOnce.Do(func() {
		file_quran_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quran_proto_rawDesc), len(file_quran_proto_rawDesc)))
	})
	return file_quran_proto_rawDescData
}

var file_quran_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quran_proto_goTypes = []any{
	(*Empty)(nil),               // 0: quran.Empty
	(*Surah)(nil),               // 1: quran.Surah
	(*Ayah)(nil),                // 2: quran.Ayah
	(*SurahListResponse)(nil),   // 3: quran.SurahListResponse
	(*SurahDetailRequest)(nil),  // 4: quran.SurahDetailRequest
	(*SurahDetailResponse)(nil), // 5: quran.SurahDetailResponse
}
var file_quran_proto_depIdxs = []int32{
	1, // 0: quran.SurahListResponse.surahs:type_name -> quran.Surah
	1, // 1: quran.SurahDetailResponse.surah:type_name -> quran.Surah
	2, // 2: quran.SurahDetailResponse.ayahs:type_name -> quran.Ayah
	0, // 3: quran.QuranService.GetAllSurahs:input_type -> quran.Empty
	4, // 4: quran.QuranService.GetSurahDetail:input_type -> quran.SurahDetailRequest
	3, // 5: quran.QuranService.GetAllSurahs:output_type -> quran.SurahListResponse
	5, // 6: quran.QuranService.GetSurahDetail:output_type -> quran.SurahDetailResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_quran_proto_init() }
func file_quran_proto_init() {
	if File_quran_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quran_proto_rawDesc), len(file_quran_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quran_proto_goTypes,
		DependencyIndexes: file_quran_proto_depIdxs,
		MessageInfos:      file_quran_proto_msgTypes,
	}.Build()
	File_quran_proto = out.File
	file_quran_proto_goTypes = nil
	file_quran_proto_depIdxs = nil
}
